spring:
  application:
    name: daehan-back
  datasource:
    url: jdbc:mysql://localhost:3306/daehan
    username: root
    password: xoals1004!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: admin
      password: admin123
  jpa:
    hibernate:
      ddl-auto: create  # 개발 초기 단계.. 후에 update로 바꾸자 일단.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  secret: vG8X7sFJ2jM6Q/Z7pTh5CZGq7Q1JmJj2k8Q6v5Ojlmo= # 32바이트 이상
  token-validity-in-seconds: 3600 # 1시간 (초 단위)

server:
  port: 8081